[build]
  command = ""          # KHÔNG chạy build
  publish = "."         # hoặc "public" nếu bạn phục vụ từ /public

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"


[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true

# Admin app (static)
[[redirects]]
  from = "/admin"
  to   = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to   = "/admin/index.html"
  status = 200



